#!/bin/bash
build ()
{
  # if TMPDIR is set leave it alone otherwise set
  [ -z $TMPDIR ] && TMPDIR='/tmp/mkinitcpio-ddns'

  # check if TMPDIR exsists if not make it
  [ -d $TMPDIR ] || mkdir -p $TMPDIR

  umask 0022

  add_full_dir /etc/ssl/certs
  add_full_dir /etc/ca-certificates
  add_file /etc/duckdns.d/default
  # add the libraries needed for name resolution
  add_file /usr/lib/libresolv.so.2
  add_file /usr/lib/libnss_dns.so.2
  # this library is needed by the binary, but it's not linked to it
  #add_file /usr/lib32/libgcc_s.so.1
  add_binary /usr/bin/jq
  add_binary /usr/bin/curl


  add_runscript
}

help ()
{
    cat<<HELPEOF
This hook is used to upload the IP address of the machine to DuckDNS.
HELPEOF
}
